[module.hugoVersion]
min = "0.119.0"

[params.images]
class_name = "img-fluid"
alignment_center_class_name = "d-block text-center"
alignment_start_class_name = "float-start me-2"
alignment_end_class_name = "float-end ms-2"
figure_class_name = "figure"
figure_caption_class_name = "figure-caption"
figure_image_class_name = "figure-img"
modern_format = "webp"
